version: '3.8'

services:
  chess_server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/chessdream?authSource=admin
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - RUST_LOG=info
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - chess-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: chess
    volumes:
      - mongodb_data:/data/db
    networks:
      - chess-network

volumes:
  mongodb_data:

networks:
  chess-network:
    driver: bridge