version: '3.8'

services:
  chess_server:
    build: .
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI=mongodb+srv://pukarkhanal:123123123456@chessdream.f1ndo47.mongodb.net
      - RUST_LOG=info
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - chess-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: pukarkhanal
      MONGO_INITDB_ROOT_PASSWORD: 123123123456
      MONGO_INITDB_DATABASE: chessdream
    volumes:
      - mongodb_data:/data/db
    networks:
      - chess-network

volumes:
  mongodb_data:

networks:
  chess-network:
    driver: bridge